"""
research_synthesizer/latex_writer.py
Generate a professional LaTeX literature review document.
"""
import os
import re
from datetime import datetime
from jinja2 import Template
from rich.console import Console

console = Console()

# ── LaTeX template ────────────────────────────────────────────────────────────

LATEX_TEMPLATE = r"""
\documentclass[12pt,a4paper]{article}

%% Packages
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{hyperref}
\usepackage{natbib}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{abstract}
\usepackage{fancyhdr}
\usepackage{xcolor}

\geometry{margin=1in}

\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    urlcolor=cyan,
    citecolor=red
}

\pagestyle{fancy}
\fancyhf{}
\rhead{Agentic RAG -- Literature Review}
\lhead{\thepage}

\title{
    \textbf{\Large {{ title }}} \\[0.5em]
    \large A Systematic Literature Review
}
\author{
    Autonomous Research Synthesizer \\
    \texttt{Agentic RAG System}
}
\date{Generated: {{ date }}}

\begin{document}

\maketitle
\tableofcontents
\newpage

%% ──────────────────────────────────────────────────────────────
\section{Executive Summary}
%% ──────────────────────────────────────────────────────────────

This literature review was autonomously generated by the Agentic RAG Research Synthesizer.
It analyzes \textbf{ {{ n_papers }} } papers on the topic: \textit{``{{ topic }}''}.
The papers were retrieved from ArXiv and Google Scholar, downloaded, and analyzed using
large language model reasoning.

%% ──────────────────────────────────────────────────────────────
\section{Synthesized Literature Review}
%% ──────────────────────────────────────────────────────────────

{{ synthesis_body }}

%% ──────────────────────────────────────────────────────────────
\section{Individual Paper Analyses}
%% ──────────────────────────────────────────────────────────────

{% for paper in papers %}
\subsection{ {{ paper.title | latex_escape }} }

\noindent\textbf{Authors:} {{ paper.authors | join(', ') | latex_escape }} \\
\noindent\textbf{Published:} {{ paper.published }} \\
\noindent\textbf{Source:} \url{ {{ paper.url }} } \\[0.5em]

{% if paper.analysis %}
\noindent\textbf{Problem Statement:} \\
{{ paper.analysis.problem_statement | latex_escape }}

\noindent\textbf{Methodology:} \\
{{ paper.analysis.methodology | latex_escape }}

\noindent\textbf{Key Contributions:}
\begin{itemize}[leftmargin=*]
{% for line in paper.analysis.key_contributions.split('\n') %}
{% if line.strip() and line.strip() not in ['-', '*', '•'] %}
    \item {{ line.strip().lstrip('-•* ') | latex_escape }}
{% endif %}
{% endfor %}
\end{itemize}

\noindent\textbf{Results:} \\
{{ paper.analysis.results | latex_escape }}

\noindent\textbf{Limitations:} \\
{{ paper.analysis.limitations | latex_escape }}

\noindent\textbf{Future Work:} \\
{{ paper.analysis.future_work | latex_escape }}
{% else %}
\noindent\textbf{Abstract:} \\
{{ paper.abstract | latex_escape }}
{% endif %}

\medskip\hrule\medskip

{% endfor %}

%% ──────────────────────────────────────────────────────────────
\section{Paper Metadata Table}
%% ──────────────────────────────────────────────────────────────

\begin{table}[h!]
\centering
\begin{tabular}{@{}p{6cm}p{3cm}p{2cm}p{2cm}@{}}
\toprule
\textbf{Title} & \textbf{First Author} & \textbf{Year} & \textbf{Source} \\
\midrule
{% for paper in papers %}
{{ paper.title[:50] | latex_escape }} \ldots & {{ (paper.authors[0] if paper.authors else 'Unknown') | latex_escape }} & {{ paper.published[:4] }} & {{ paper.source }} \\
{% endfor %}
\bottomrule
\end{tabular}
\caption{Papers included in this literature review.}
\end{table}

\end{document}
"""


def latex_escape(text: str) -> str:
    """Escape special LaTeX characters."""
    if not text:
        return ""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&",  r"\&"),
        ("%",  r"\%"),
        ("$",  r"\$"),
        ("#",  r"\#"),
        ("_",  r"\_"),
        ("{",  r"\{"),
        ("}",  r"\}"),
        ("~",  r"\textasciitilde{}"),
        ("^",  r"\textasciicircum{}"),
    ]
    for char, replacement in replacements:
        text = text.replace(char, replacement)
    return text


def write_latex(topic: str, papers: list[dict], synthesis: str, output_dir: str) -> str:
    """Render and save the LaTeX document. Returns filepath."""
    os.makedirs(output_dir, exist_ok=True)

    env = Template(LATEX_TEMPLATE)
    env.globals = {}

    # Register custom filter
    from jinja2 import Environment
    jinja_env = Environment()
    jinja_env.filters["latex_escape"] = latex_escape
    template   = jinja_env.from_string(LATEX_TEMPLATE)

    # Sanitize synthesis body for LaTeX
    synthesis_body = latex_escape(synthesis)

    rendered = template.render(
        title          = f"Literature Review: {topic}",
        topic          = topic,
        date           = datetime.now().strftime("%B %d, %Y"),
        n_papers       = len(papers),
        papers         = papers,
        synthesis_body = synthesis_body,
        latex_escape   = latex_escape,
    )

    # Safe filename
    safe_topic = re.sub(r"[^\w\s-]", "", topic)[:40].strip().replace(" ", "_")
    filename   = f"literature_review_{safe_topic}.tex"
    filepath   = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(rendered)

    console.print(f"  [green]✔ LaTeX saved:[/green] {filepath}")
    return filepath
